### ISSUE TITLE
Scaladoc template info and compilation

### ISSUE THREAD

**Issue by mkosunen** [Chisel-blocks/chisel-blocks-utils#4]
@chiplet , as a result of your current work, could you add a brief scaladoc example to initmodule, and add a 'doc' recipe to buid it. If possible, add also a link to scaladoc syntax documentation to your example.
Thanks.

**Comment by mkosunen** [comment]
@chiplet , Could you add a brief scaladoc example to initmodule, and add a 'doc' recipe to buid it. If possible, add also a link to scaladoc syntax documentation to your example. 
Thanks.

**Comment by chiplet** [comment]
This has been implemented in PR #5.
